export const ENDPOINTS = {
    GET_EVENTS_FATALITIES: "/get-events-fatalities",
    GET_EVENTS_YEAR: "/get-events-year",
    GET_DATA_BY_PERIOD: "/get-data-by-period",
    GET_AVAILABLE_DATES: "/get-available-dates",
    GET_EVENT_GRAPH: "/get-event-graph",
    GET_FILTERED_BY_ACTOR_NAMES: "/get-filtered-by-actor-names",
    GET_REPORTS_BY_FILTERS: "/get-reports-by-filters",
    GET_FULL_ACTORS: "/get-full-actors",
    GET_EVENT_TYPE_COLOURS: "/get-event-type-colours",
    SET_EVENT_TYPE_COLOURS: "/set-event-type-colours",
    GET_LINK_TYPE_COLOURS: "/get-link-type-colours",
    SET_LINK_TYPE_COLOURS: "/set-link-type-colours",
    GET_PERIOD_INFO: "/get-period-info",
    GET_ACTOR_TIMELINE: "/get-actor-timeline",
    GET_CENTROID_LOCATION: "/get-centroid-location",
    GET_MAP_OVERLAY: "/get-map-overlay",
    GET_COUNTRY_STATISTICS: "/get-country-statistics",
    GET_COUNTRY_TIMELINE: "/get-country-timeline",
    GET_DYAD_TEXT: "/get-dyad-text",
    GET_PEACE_DATA: "/get-peace-data",
    GET_NEGOTIATIONS_AGREEMENTS: "/get-negotiations-agreements",
  };
  